[package]
name = "httpstat"
version = "0.1.0"
authors = ["ktr0731 <aizu.s1230022@gmail.com>"]

[dependencies]
url = "1.7.0"
serde = "1.0.64"
serde_json = "1.0.19"
serde_derive = "1.0.64"
tempfile = "3"
colored = "1.6"
rand = "0.5"
